// CONTROL STATEMENT---------------------

// // if-else
// the if statement is excutes a statement if a specified condition is truthy.\
// if the condition is falsy another statement is false

// var tom = 'rain';

// if(tom=='rain'){
// console.log('take a raincoat');
// }else{
// console.log('No need to take a raincoat');
// }

// WRITE A PROGRAM THAT WORKS OUT WHEATHER IF A GIVEN YEAR IS A LEAP YEARS OR NOT?

// var yr =2021;
// debugger;
// if(yr % 4=== 0){
// if(yr % 100 === 0){
// if(yr %400 === 0){
// console.log('the year'+yr+'is a leap year');
// }else{
//     console.log('This year is '+yr+' not leap year');
// }
// }else{
//     console.log('this is a '+yr+'leap year');
// }
// }else{
// console.log('the year is '+yr+' not leap year');
// }


// WHAT IS TRUTHY AND FALSY VALUES IN JAVASCRIPT?
// we have total 5 falsy value in JAVASCRIPT
// 0,'',undefined,null,NaN,false** is false anyway 


if(score=3){
    console.log('OMG , we loss the match');
}else{
    console.log('yay we won the match');
}
