// EXPRESSIONS AND OPERATORS---------------------------------------------------------------

console.log(5+8);// 5:operand +:operator  ans=(Expression) (=) Assiment opretor

// 1 Assignment operator

// An Assignment operator assign a value to its left operand 
// based on the value of its right operand
// The simple assignment operator is equal (=)
var x =5;
var y=5;
console.log(x==y);

console.log(`is this is a:${x==y}`);

// 2 Arithmetic operators

// An Arithmetic operator takes numerical values
// (either literals or variable)as their operands and returns a single numberical value.

console.log(3+3);
console.log(10-6);
console.log(20/5);
console.log(5*8);
 console.log("remender operetor" + 28%7);

 